themes:
  - name: "nordic"
    colors:
      - "#191D24"
      - "#1E222A"
      - "#222630"
      - "#242933"
      - "#2E3440"
      - "#3B4252"
      - "#434C5E"
      - "#4C566A"
      - "#60728A"
      - "#BBC3D4"
      - "#C0C8D8"
      - "#D8DEE9"
      - "#E5E9F0"
      - "#ECEFF4"
      - "#5E81AC"
      - "#81A1C1"
      - "#88C0D0"
      - "#8FBCBB"
      - "#9FC6C5"
      - "#80B3B2"
      - "#BF616A"
      - "#C5727A"
      - "#B74E58"
      - "#D08770"
      - "#D79784"
      - "#CB775D"
      - "#EBCB8B"
      - "#EFD49F"
      - "#E7C173"
      - "#A3BE8C"
      - "#B1C89D"
      - "#97B67C"
      - "#B48EAD"
      - "#BE9DB8"
      - "#A97EA1"
