"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─ ](bold fg:color_border)\
[](fg:color_bg1)\
$username\
[  ](bg:color_bg1 fg:color_arch)\
[](bg:color_bg2 fg:color_bg1)\
$directory\
$git_branch\
$git_status\
[](fg:color_bg2)\
$line_break\
[╰─ ](bold fg:color_border)\
$character"""

palette = 'arch_photo_theme'

[palettes.arch_photo_theme]
color_border = '#6c7086'     
color_bg1 = '#313244'        
color_bg2 = '#bac2de'       
color_arch = '#89dceb'       
color_text_light = '#cdd6f4' 
color_text_dark = '#1e1e2e' 
color_prompt = '#a6e3a1'    

[username]
show_always = true
style_user = "bg:color_bg1 fg:color_text_light"
format = '[ $user]($style)'

[directory]
style = "bg:color_bg2 fg:color_text_dark bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = '[❯](bold fg:color_prompt)'
error_symbol = '[❯](bold fg:#f38ba8)'

[git_branch]
style = "bg:color_bg2 fg:color_text_dark"
format = '[  $branch]($style)'

[git_status]
style = "bg:color_bg2 fg:color_text_dark bold"
format = '[ $all_status$ahead_behind]($style)'
